# Generated by Django 5.1 on 2024-09-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, help_text='Загрузите превью статьи', null=True, upload_to='article/photo', verbose_name='Фото'),
        ),
    ]
