# Generated by Django 5.1 on 2024-08-16 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата производства продукта"
            ),
        ),
    ]
