# Generated by Django 4.2.2 on 2024-09-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category"],
                "permissions": [
                    ("can_edit_category", "Can edit any category"),
                    ("can_edit_description", "Can edit any description"),
                    ("can_unpublish_product", "Can unpublish of a product"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="Опубликованные товары"
            ),
        ),
    ]
